### ISSUE TITLE
running frontend error

### ISSUE THREAD

**Issue by yingfc** [Monacr/FitSocial#13]
**Describe the bug**
Error when running frontend server after backend server is up

**To Reproduce**
I followed the README instructions and installed npm, rust. and installed node modules via `npm i`
Backend server works fine, frontend server is saying missing module

**Expected behavior**
Frontend server should be up for user interaction

**Actual behavior**
Frontend server error

**Additional context**
<img width="864" alt="image" src="https://user-images.githubusercontent.com/66505438/221664507-2b9d6cdf-2778-4c2f-8be2-aaba07b1b2aa.png">

**Comment by Lawqup** [comment]
Can you tell me what happens when running `npm i @expo/config/paths`?

**Comment by yingfc** [comment]
I am able to run npm after manually installing this dependency, but the browser is blank, and here is the log from frontend
[fitSocial-log.txt](https://github.com/Monacr/FitSocial/files/10845413/fitSocial-log.txt)

**Comment by Lawqup** [comment]
The browser thing is a different issue. I can't reproduce the not-installed dependency issue when reset npm and `node_modules` for the frontend, so I'm going to mark as fixed for now.
