### ISSUE TITLE
Frontend npm start failed with not found assets and module import error

### ISSUE THREAD

**Issue by linqiu0-0** [Monacr/FitSocial#19]
**Describe the bug**
The Frontend build failed with an error. 

**To Reproduce**
Whether the bug can be reproduced at will, occasionally, or not at all
1. Run `npm i` in the frontend folder
2. Run `npm start`
3. Press `i` to use emulators
```
Unable to resolve asset "./assets/splash.png" from "splash.image" in your app.json or app.config.js
iOS Bundling failed 11970ms
Unable to resolve "react-native-svg" from "node_modules/react-native-chart-kit/dist/PieChart.js
```

**Expected behavior**
It should work with no error. 

**Actual behavior**
In the emulator, we could also see this 
<img width="320" alt="Screen Shot 2023-02-28 at 4 06 19 PM" src="https://user-images.githubusercontent.com/73025661/222011366-dce57c0b-3666-4d95-b8b9-3b60463af667.png">
<img width="308" alt="Screen Shot 2023-02-28 at 4 06 34 PM" src="https://user-images.githubusercontent.com/73025661/222011392-b1634781-4625-4071-83ab-52166da04071.png">

**Additional context**
There isn't a file called splash.png in the asset folder. Do we need to add one?
For the modules import error, do we need to install other modules beyond the package.json?

**Comment by Lawqup** [comment]
1. Don't worry about the splash screen stuff, it's just a warning that we don't have a splash screen picture.

2. I guess try `npm i react-native-svg`. The stuff in the package.json should be sufficient but because npm is the worst package manager in existence sometimes it misses stuff. We'll look at a more permanent fix.

**Comment by linqiu0-0** [comment]
Works after run `npm i react-native-svg`!
