### ISSUE TITLE
Sign up function not working

### ISSUE THREAD

**Issue by linqiu0-0** [Monacr/FitSocial#20]
**Describe the bug**
Cannot click the sign up button 

**To Reproduce**
Whether the bug can be reproduced at will, occasionally, or not at all
1. Go to the sign up page
2. Enter all required value
3. No response when clicking on the signup button 

**Expected behavior**
Should go to other page or say why it does not work 

**Actual behavior**
No error but also no response after typing all required fields

<img width="313" alt="Screen Shot 2023-02-28 at 4 35 44 PM" src="https://user-images.githubusercontent.com/73025661/222014954-aaf555b7-1f5a-432f-8d6d-df12b8c4775d.png">

**Additional context**
It would also be helpful to have some placeholder in the text field. It confused me what needs to be entered initially.
Should this button change to a brighter version when I click it? Or is there supposed to be some other behavior?

**Comment by Lawqup** [comment]
Do you have the backend running? Right now the sign up screen works for me. Do you have a space at the end of your username? There is a known bug where the error message doesn't appear when using autocomplete (and then an automatic space at the end) for the username.

And we actually do have placeholders in the text field, but we were testing color schemes out and need to make the text lighter on the dark background :).

**Comment by linqiu0-0** [comment]
You are right. It works now!
